## Need to install RESR Client in VS Code.


## Total same fecth address, header data type and data.


# Sign Up
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "test1234"
}


###

# Sign in : Correct User Name
POST http://127.0.0.1:8000/signin
Content-Type: application/json

{ "username" : "test@test.com", "password" : "test1234"}


###


# Sign in : Wrong User Name
POST http://localhost:8000/signin
Content-Type: application/json

{ 
  "username" : "test@test.com", 
  "password" : "test"
}


###


GET http://localhost:8000/project/test

{}


### 


# Token
GET http://localhost:8000/token
Content-Type: application/json
Authorization: Token c4bed12b51740181901d557b373346a07715a8eb

{}


###


POST http://localhost:8000/project/create
Content-Type: application/json

{
    "user": 1,
    "title": "Sample Project",
    "tone": "Formal",
    "purpose": "Demonstration",
    "content": "This is a sample project to demonstrate the creation of a project via API.",
    "type": "Demo"
}



###


# Second create request.
POST http://localhost:8000/project/create
Content-Type: application/json

{
    "user": 1,
    "title": "Sample Project 2",
    "tone": "Formal",
    "purpose": "Demonstration",
    "content": "This is a sample project to demonstrate the creation of a project via API.",
    "type": "Demo"
}


###


GET http://localhost:8000/project/show_all_projects/1


###


GET http://localhost:8000/project/show_detail/1




