## Need to install RESR Client in VS Code.


## Total same fecth address, header data type and data.


# Sign Up
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "test1234"
}


###

# Sign in : Correct User Name
POST http://127.0.0.1:8000/signin
Content-Type: application/json

{ "username" : "test@test.com", "password" : "test1234"}


###
# ### must add between test code. Otherwise, it will not work.

# Sign in : Wrong User Name
POST http://localhost:8000/signin
Content-Type: application/json

{ "username" : "test@test.com", "password" : "test"}


### 


# Token
GET http://localhost:8000/token
Content-Type: application/json
Authorization: Token c4bed12b51740181901d557b373346a07715a8eb

{}
